name: Make artifact

on:
  push:
    branches: [main, feat]

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: list files
        run: ls
      - name: upload
        uses: actions/upload-artifact@v4
        with: 
         name: fajlovi
         path: ./
      - name: sleep a little
        run: sleep 20
  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
      
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
         name: fajlovi
         path: ./ovde/stavi
      - name: list files
        run: |
          ls
          cd ovde
          ls
          cd stavi