name: My manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: Your name
        type: string
        default: Some name
      surname:
        description: Your surname
        type: string
        default: Some surname
        required: true
      fav_color:
        description: Favourite color
        type: choice
        options:
          - blue
          - red
          - green

jobs:
  ispis:
    runs-on: ubuntu-latest
    steps:
    - name: first step
      run: echo "Hello from the first step!"
    - name: second step
      run: echo "Hello fromn the second step!"
    - name: print inputs
      run: |
        echo Name: ${{ inputs.name }}
        echo Surname: ${{ inputs. surname }}
        echo Favourite color: ${{ inputs.fav_color }}
