name: Random workflow
on:
  workflow_dispatch:
  push:
    branches: [main, feat]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Greeting
      run: echo "Hello world from random workflow!"